language: c
sudo: required
dist: trusty
services:
  - docker
env:
  - TR_ARCH=local       GCOV=1
  - TR_ARCH=local       GCOV=0  CLANG=1
  - TR_ARCH=x86_64      GCOV=1
  - TR_ARCH=armv7hf     GCOV=1
  - TR_ARCH=aarch64     GCOV=1
  - TR_ARCH=ppc64le     GCOV=1
  - TR_ARCH=alpine      GCOV=1
script:
  - sudo make -C scripts/travis $TR_ARCH
after_success:
  - make -C scripts/travis after_success
