name: CentOS Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target: [centos7, centos8]

    steps:
    - uses: actions/checkout@v2
    - name: Run CentOS ${{ matrix.target }} Test
      shell: 'script -q -e -c "bash {0}"' # provide a terminal
      run: sudo -E make -C scripts/ci ${{ matrix.target }}
