name: Compat Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        compiler: [GCC, CLANG]


    steps:
    - uses: actions/checkout@v2
    - name: Run Compat Tests (${{ matrix.compiler }})
      run: sudo -E make -C scripts/ci local COMPAT_TEST=y ${{ matrix.compiler }}=1
